# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/SOC_1/SOC_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_1 || ORIG_REF_NAME==SOC_1} -quiet] -quiet

# IP: bd/SOC_1/ip/SOC_1_zynq_ultra_ps_e_0_0/SOC_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==SOC_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/SOC_1/ip/SOC_1_H_Accerlation_IP_v1_0_0_0/SOC_1_H_Accerlation_IP_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_1_H_Accerlation_IP_v1_0_0_0 || ORIG_REF_NAME==SOC_1_H_Accerlation_IP_v1_0_0_0} -quiet] -quiet

# IP: d:/TAI_LIEU/DU_AN_XU_LY_TINHIEU/XU_LY_TIN_HIEU_FPGA/IP_FPGA/H_function/SOC_1/SOC_1.gen/sources_1/bd/SOC_1/ip/SOC_1_H_Accerlation_IP_v1_0_0_0/H_Function_ILA_IP/H_Function_ILA_IP.srcs/sources_1/ip/ila_debug/ila_debug.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_debug || ORIG_REF_NAME==ila_debug} -quiet] -quiet

# IP: bd/SOC_1/ip/SOC_1_xbar_0/SOC_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_1_xbar_0 || ORIG_REF_NAME==SOC_1_xbar_0} -quiet] -quiet

# IP: bd/SOC_1/ip/SOC_1_auto_ds_0/SOC_1_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_1_auto_ds_0 || ORIG_REF_NAME==SOC_1_auto_ds_0} -quiet] -quiet

# IP: bd/SOC_1/ip/SOC_1_auto_pc_0/SOC_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_1_auto_pc_0 || ORIG_REF_NAME==SOC_1_auto_pc_0} -quiet] -quiet

# IP: bd/SOC_1/ip/SOC_1_auto_ds_1/SOC_1_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_1_auto_ds_1 || ORIG_REF_NAME==SOC_1_auto_ds_1} -quiet] -quiet

# IP: bd/SOC_1/ip/SOC_1_auto_pc_1/SOC_1_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_1_auto_pc_1 || ORIG_REF_NAME==SOC_1_auto_pc_1} -quiet] -quiet

# IP: bd/SOC_1/ip/SOC_1_ps8_0_axi_periph_0/SOC_1_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_1_ps8_0_axi_periph_0 || ORIG_REF_NAME==SOC_1_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/SOC_1/ip/SOC_1_rst_ps8_0_99M_0/SOC_1_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SOC_1_rst_ps8_0_99M_0 || ORIG_REF_NAME==SOC_1_rst_ps8_0_99M_0} -quiet] -quiet

# XDC: d:/TAI_LIEU/DU_AN_XU_LY_TINHIEU/XU_LY_TIN_HIEU_FPGA/IP_FPGA/H_function/SOC_1/SOC_1.gen/sources_1/bd/SOC_1/ip/SOC_1_zynq_ultra_ps_e_0_0/SOC_1_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: d:/TAI_LIEU/DU_AN_XU_LY_TINHIEU/XU_LY_TIN_HIEU_FPGA/IP_FPGA/H_function/SOC_1/SOC_1.gen/sources_1/bd/SOC_1/ip/SOC_1_zynq_ultra_ps_e_0_0/SOC_1_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SOC_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==SOC_1_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/TAI_LIEU/DU_AN_XU_LY_TINHIEU/XU_LY_TIN_HIEU_FPGA/IP_FPGA/H_function/SOC_1/SOC_1.gen/sources_1/bd/SOC_1/ip/SOC_1_H_Accerlation_IP_v1_0_0_0/H_Function_ILA_IP/H_Function_ILA_IP.srcs/sources_1/ip/ila_debug/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_debug || ORIG_REF_NAME==ila_debug} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/TAI_LIEU/DU_AN_XU_LY_TINHIEU/XU_LY_TIN_HIEU_FPGA/IP_FPGA/H_function/SOC_1/SOC_1.gen/sources_1/bd/SOC_1/ip/SOC_1_H_Accerlation_IP_v1_0_0_0/H_Function_ILA_IP/H_Function_ILA_IP.srcs/sources_1/ip/ila_debug/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_debug || ORIG_REF_NAME==ila_debug} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/TAI_LIEU/DU_AN_XU_LY_TINHIEU/XU_LY_TIN_HIEU_FPGA/IP_FPGA/H_function/SOC_1/SOC_1.gen/sources_1/bd/SOC_1/ip/SOC_1_H_Accerlation_IP_v1_0_0_0/H_Function_ILA_IP/H_Function_ILA_IP.srcs/sources_1/ip/ila_debug/ila_debug_ooc.xdc

# XDC: d:/TAI_LIEU/DU_AN_XU_LY_TINHIEU/XU_LY_TIN_HIEU_FPGA/IP_FPGA/H_function/SOC_1/SOC_1.gen/sources_1/bd/SOC_1/ip/SOC_1_xbar_0/SOC_1_xbar_0_ooc.xdc

# XDC: d:/TAI_LIEU/DU_AN_XU_LY_TINHIEU/XU_LY_TIN_HIEU_FPGA/IP_FPGA/H_function/SOC_1/SOC_1.gen/sources_1/bd/SOC_1/ip/SOC_1_auto_ds_0/SOC_1_auto_ds_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SOC_1_auto_ds_0 || ORIG_REF_NAME==SOC_1_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/TAI_LIEU/DU_AN_XU_LY_TINHIEU/XU_LY_TIN_HIEU_FPGA/IP_FPGA/H_function/SOC_1/SOC_1.gen/sources_1/bd/SOC_1/ip/SOC_1_auto_ds_0/SOC_1_auto_ds_0_ooc.xdc

# XDC: d:/TAI_LIEU/DU_AN_XU_LY_TINHIEU/XU_LY_TIN_HIEU_FPGA/IP_FPGA/H_function/SOC_1/SOC_1.gen/sources_1/bd/SOC_1/ip/SOC_1_auto_pc_0/SOC_1_auto_pc_0_ooc.xdc

# XDC: d:/TAI_LIEU/DU_AN_XU_LY_TINHIEU/XU_LY_TIN_HIEU_FPGA/IP_FPGA/H_function/SOC_1/SOC_1.gen/sources_1/bd/SOC_1/ip/SOC_1_auto_ds_1/SOC_1_auto_ds_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SOC_1_auto_ds_1 || ORIG_REF_NAME==SOC_1_auto_ds_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/TAI_LIEU/DU_AN_XU_LY_TINHIEU/XU_LY_TIN_HIEU_FPGA/IP_FPGA/H_function/SOC_1/SOC_1.gen/sources_1/bd/SOC_1/ip/SOC_1_auto_ds_1/SOC_1_auto_ds_1_ooc.xdc

# XDC: d:/TAI_LIEU/DU_AN_XU_LY_TINHIEU/XU_LY_TIN_HIEU_FPGA/IP_FPGA/H_function/SOC_1/SOC_1.gen/sources_1/bd/SOC_1/ip/SOC_1_auto_pc_1/SOC_1_auto_pc_1_ooc.xdc

# XDC: d:/TAI_LIEU/DU_AN_XU_LY_TINHIEU/XU_LY_TIN_HIEU_FPGA/IP_FPGA/H_function/SOC_1/SOC_1.gen/sources_1/bd/SOC_1/ip/SOC_1_rst_ps8_0_99M_0/SOC_1_rst_ps8_0_99M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SOC_1_rst_ps8_0_99M_0 || ORIG_REF_NAME==SOC_1_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/TAI_LIEU/DU_AN_XU_LY_TINHIEU/XU_LY_TIN_HIEU_FPGA/IP_FPGA/H_function/SOC_1/SOC_1.gen/sources_1/bd/SOC_1/ip/SOC_1_rst_ps8_0_99M_0/SOC_1_rst_ps8_0_99M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SOC_1_rst_ps8_0_99M_0 || ORIG_REF_NAME==SOC_1_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/TAI_LIEU/DU_AN_XU_LY_TINHIEU/XU_LY_TIN_HIEU_FPGA/IP_FPGA/H_function/SOC_1/SOC_1.gen/sources_1/bd/SOC_1/SOC_1_ooc.xdc
